api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('admin/', admin.site.urls),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from bases.views import Home, HomeSinPrivilegios

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True) # Fecha de Creación con auto_now_add sólo se agregará este campo cuando se crea un registro
    fm = models.DateTimeField(auto_now=True) # Fecha de Modificación con auto_now se modificará esta fecha cada vez que se modifique algún campo del registro
    uc = models.ForeignKey(User, on_delete=models.CASCADE) # Usuario que crea el registro, este será el id que se asociará al Usuario
    um = models.IntegerField(blank=True, null=True) # Usuario modifica este campo sera integer que guardará el id de la tabla User
    
    
    class Meta:
        abstract = True # Al agregar abstract = True este modelo no va a ser tenido en cuenta a la hora de realizar las migraciones, pero si se va a poder heredar del mismo


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True) # Fecha de Creación con auto_now_add sólo se agregará este campo cuando se crea un registro
    fm = models.DateTimeField(auto_now=True) # Fecha de Modificación con auto_now se modificará esta fecha cada vez que se modifique algún campo del registro
    #uc = models.ForeignKey(User, on_delete=models.CASCADE) # Usuario que crea el registro, este será el id que se asociará al Usuario
    #um = models.IntegerField(blank=True, null=True) # Usuario modifica este campo sera integer que guardará el id de la tabla User
    uc = UserForeignKey(auto_user_add=True, related_name='+') # con el más no va a asignar un nombre a la búsqueda que vamos a hacer
    um = UserForeignKey(auto_user=True, related_name='+')
    
    class Meta:
        abstract = True # Al agregar abstract = True este modelo no va a ser tenido en cuenta a la hora de realizar las migraciones, pero si se va a poder heredar del mismo        

bases/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy

# Create your views here.

class MixinFormInvalid:
    def form_invalid(self, form):
        response = super().form_invalid(form)
        # Esto es para validar si el formulario se envía por medio de Ajax
        #if self.request.is_ajax():
        if self.request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse(form.errors, status=400)
        else:
            return response


class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin, MixinFormInvalid):
    login_url = 'bases:login'
    raise_exception = False
    redirect_field_name = 'redirect_to'

    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user==AnonymousUser():
            self.login_url = 'bases:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

class HomeSinPrivilegios(LoginRequiredMixin, generic.TemplateView):
    login_url= 'bases:login'
    template_name = "bases/sin_privilegios.html"

bases/templates/bases/home.html
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %}


{% block side_bar %}
    
{% endblock side_bar %}


{% block top_bar %}
    
{% endblock top_bar %}
    

{% block page_content %}
    
{% endblock page_content %}


{% block footer %}
    
{% endblock footer %}
        

{% block login %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    <small class="text-danger">
                                        
                                        
                                            
                                    </small>
                                </div>
                                <form class="user" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control form-control-user"
                                            id="id_username" name="username" aria-describedby="emailHelp"
                                            placeholder="Usuario">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            id="id_password" name="password" placeholder="Password">
                                    </div>

                                    {#{ form.as_p }#} 
                                    

                                    <button type="submit" class="btn btn-primary btn-user btn-block">Acceder</button>
                                    </div>
                                    
                                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
    
{% endblock login %}

{% block js_page %}
<script>
    {% if form.errors %}
                                            
        {% for field in form %}
            
            {% if field.errors %}
                
                {% for error in field.errors  %}
                    
                    mensaje('{{ error|escape }}', 'red');
                {% endfor %}
                    
            {% endif %}
                
        {% endfor %}
            
    {% endif %}

    {% if form.non_field_errors %}
        
        {% for error in form.non_field_errors %}
            
            mensaje('{{ error|escape }}', 'red');
                
        {% endfor %}
            
    {% endif %}
</script>

{% endblock js_page %}
    

bases/templates/bases/sin_privilegios.html
{% extends 'base/base.html' %}
{% block page_content %}
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Usuario: <mark>{{ user.username }}  {{user.get_full_name }}</mark> 
                </div>
                <div class="dropdown-divider"></div>

                <div class="row">
                    <mark>No tiene suficientes privilegios</mark> para cargar la opción solicitada.
                    <br>
                    <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>

                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir a Inicio</a>
                        <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con otro Usuario</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}